require 'test_map_reader'

class TestMapReader1900 < Test::Unit::TestCase
  include MapReaderTest
  
  def setup
    setup_reader
    @powers = [
      {
        :name => 'Austria',
        :own_word => 'Austrian',
        :abbreviation => 'A',
        :homes => ['BUD', 'TRI', 'VIE'],
        :owns => ['BUD', 'TRI', 'VIE'],
        :units=>[army('BUD'),army('VIE'),army('TRI')],
      },
      {
        :name => 'Britain',
        :own_word => 'British',
        :abbreviation => 'B',
        :homes => ['EDI', 'LON', 'LVP'],
        :owns => ['EDI', 'EGY', 'LON', 'LVP'],
        :units => [fleet('EDI'), fleet('EGY'), fleet('LON'), fleet('GIB')],
      },
      {
        :name => 'France',
        :own_word => 'French',
        :abbreviation => 'F',
        :homes => ['BRE', 'MAR', 'PAR'],
        :owns => ['ALG', 'BRE', 'MAR', 'PAR',],
        :units => [army('ALG'), fleet('BRE'), army('MAR'), army('PAR'),],
      },
      {
        :name => 'Germany',
        :own_word => 'German',
        :abbreviation => 'G',
        :homes => ['BER', 'COL', 'KIE',  'MUN'],
        :owns => ['BER', 'COL', 'KIE',  'MUN'],
        :units => [army('BER'), army('COL'), fleet('KIE'),  army('MUN')],
      },
      {
        :name => 'Italy',
        :own_word => 'Italian',
        :abbreviation => 'I',
        :homes => ['MIL', 'NAP', 'ROM'],
        :owns => ['MIL', 'NAP', 'ROM'],
        :units => [army('MIL'), fleet('NAP'), army('ROM')],
      },
      {
        :name => 'Russia',
        :own_word => 'Russian',
        :abbreviation => 'R',
        :homes => ['MOS', 'SEV', 'STP', 'WAR'],
        :owns => ['MOS', 'SEV', 'STP', 'WAR'],
        :units => [army('MOS'), fleet('SEV'), fleet('STP/SC'), army('WAR')],
        :partisans => ['SIB'],
      },
      {
        :name => 'Turkey',
        :own_word => 'Ottoman',
        :abbreviation => 'O',
        :homes => ['ANK', 'CON', 'DAM'],
        :owns => ['ANK', 'CON', 'DAM'],
        :units => [fleet('ANK'), army('CON'), army('DAM')],
      },
    ]
    @unowned = ['BEL', 'BUL', 'DEN', 'GRE', 'MOR', 'NET', 'NWY', 'POR', 'RUM', 
                'SER', 'SPA', 'SWE', 'SWI', 'TRP',]
    @locations = [
      {:name=>'Adriatic Sea', :full_abbreviation=>'adr',:aliases=>['adriatic'],
        },
      {:name=>'Aegean Sea', :full_abbreviation=>'aeg',:aliases=>[ 'aegean' ],},
      {:name=>'Algeria',:full_abbreviation=>'alg',:aliases=>['algiers'],
        },
      {:name=>'Alsace',:full_abbreviation=>'als',:aliases=>['alsace-lorraine'],
        },
      {:name=>'Ankara',:full_abbreviation=>'ank',
        },
      {:name=>'Apulia',:full_abbreviation=>'apu',
        },
      {:name=>'Arabia',:full_abbreviation=>'ara',
        },
      {:name=>'Armenia',:full_abbreviation=>'arm',
        },
      {:name=>'Baltic Sea',:full_abbreviation=>'bal',:aliases=>['baltic'],
        },
      {:name=>'Barents Sea',:full_abbreviation=>'bar',:aliases=>['barents'],
        },
      {:name=>'Belgium',:full_abbreviation=>'bel',
        },
      {:name=>'Berlin',:full_abbreviation=>'ber',
        },
      {:name=>'Black Sea',:full_abbreviation=>'bla',:aliases=>['black'],
        },
      {:name=>'Bohemia',:full_abbreviation=>'boh',
        },
      {:name=>'Bosnia',:full_abbreviation=>'bos',
        },
      {:name=>'Brest',:full_abbreviation=>'bre',
        },
      {:name=>'Budapest',:full_abbreviation=>'bud',
        },
      {:name=>'Bulgaria',:full_abbreviation=>'bul',
        },
      {:name=>'Burgundy',:full_abbreviation=>'bur',
        },
      {:name=>'Clyde',:full_abbreviation=>'cly',
        },
      {:name=>'Cologne',:full_abbreviation=>'col',:aliases=>[ 'ruh', 'ruhr'],
        },
      {:name=>'Constantinople',:full_abbreviation=>'con',
        },
      {:name=>'Cyrenaica',:full_abbreviation=>'cyr',
        },
      {:name=>'Damascus',:full_abbreviation=>'dam',:aliases=>['syr', 'syria'],
        },
      {:name=>'Denmark',:full_abbreviation=>'den',
        },
      {:name=>'Eastern Mediterranean',:full_abbreviation=>'eas',:aliases=>['emed', 'east', 'eastern', 'eastmed', 'ems', 'eme', 'emd'],
        },
      {:name=>'Edinburgh',:full_abbreviation=>'edi',},
      {:name=>'Egypt',:full_abbreviation=>'egy',},
      {:name=>'English Channel',:full_abbreviation=>'eng',:aliases=>[ 'english', 'channel', 'ech'],},
      {:name=>'Finland',:full_abbreviation=>'fin',},
      {:name=>'Galicia',:full_abbreviation=>'gal',},
      {:name=>'Gascony',:full_abbreviation=>'gas',},
      {:name=>'Gibraltar',:full_abbreviation=>'gib',:aliases=>['rock'],},
      {:name=>'Greece',:full_abbreviation=>'gre',},
      {:name=>'Gulf of Bothnia',:full_abbreviation=>'bot',:aliases=>[ 'gbo', 'gob', 'both', 'gulfofb', 'bothnia'],},
      {:name=>'Gulf of Lyon',:full_abbreviation=>'lyo',:aliases=>[ 'gly', 'gol', 'gulfofl', 'lyon'],},
      {:name=>'Hejaz',:full_abbreviation=>'hej',},
      {:name=>'Helgoland Bight',:full_abbreviation=>'hel',:aliases=>[ 'helgoland', 'heligoland', 'heligoland bight'],},
      {:name=>'Iceland',:full_abbreviation=>'ice',},
      {:name=>'Ionian Sea',:full_abbreviation=>'ion',:aliases=>[ 'ionian'],},
      {:name=>'Ireland',:full_abbreviation=>'ire',},
      {:name=>'Irish Sea',:full_abbreviation=>'iri',:aliases=>[ 'irish'],},
      {:name=>'Kiel',:full_abbreviation=>'kie',},
      {:name=>'Konya',:full_abbreviation=>'kon',},
      {:name=>'Liverpool',:full_abbreviation=>'lvp',:aliases=>[ 'livp', 'lpl'],},
      {:name=>'Livonia',:full_abbreviation=>'lvn',:aliases=>[ 'lvo', 'livo', 'lva'],},
      {:name=>'London',:full_abbreviation=>'lon',},
      {:name=>'Macedonia (east coast)',:full_abbreviation=>'mac/ec',:aliases=>[ 'mac(ec)', 'macedonia/ec', 'macedonia(ec)', 'mac (ec)'],},
      {:name=>'Macedonia (west coast)',:full_abbreviation=>'mac/wc',:aliases=>[ 'mac(wc)', 'macedonia/wc', 'macedonia(wc)', 'mac (wc)'],},
      {:name=>'Macedonia',:full_abbreviation=>'mac',},
      {:name=>'Marseilles',:full_abbreviation=>'mar',:aliases=>[ 'mars'],},
      {:name=>'Mid-Atlantic Ocean',:full_abbreviation=>'mao',:aliases=>[ 'mid', 'midatlanticocean', 'midatlantic', 'mat'],},
      {:name=>'Milan',:full_abbreviation=>'mil',},
      {:name=>'Morocco',:full_abbreviation=>'mor',},
      {:name=>'Moscow',:full_abbreviation=>'mos',},
      {:name=>'Munich',:full_abbreviation=>'mun',},
      {:name=>'Naples',:full_abbreviation=>'nap',},
      {:name=>'Netherlands',:full_abbreviation=>'net',:aliases=>[ 'hol', 'holland'],},
      {:name=>'North Atlantic Ocean',:full_abbreviation=>'nao',:aliases=>[ 'nat'],},
      {:name=>'North Sea',:full_abbreviation=>'nth',:aliases=>[ 'norsea', 'nts'],},
      {:name=>'Norway',:full_abbreviation=>'nwy',:aliases=>[ 'nor', 'norw'],},
      {:name=>'Norwegian Sea',:full_abbreviation=>'nwg',:aliases=>[ 'nws', 'norwegian', 'norwsea', 'nrg'],},
      {:name=>'Palestine',:full_abbreviation=>'pal',},
      {:name=>'Paris',:full_abbreviation=>'par',},
      {:name=>'Picardy',:full_abbreviation=>'pic',},
      {:name=>'Piedmont',:full_abbreviation=>'pie',},
      {:name=>'Portugal',:full_abbreviation=>'por',},
      {:name=>'Prussia',:full_abbreviation=>'pru',},
      {:name=>'Rome',:full_abbreviation=>'rom',:aliases=>[ 'roma'],},
      {:name=>'Rumania',:full_abbreviation=>'rum',},
      {:name=>'Serbia',:full_abbreviation=>'ser',},
      {:name=>'Sevastopol',:full_abbreviation=>'sev',:aliases=>[ 'sevastapol'],},
      {:name=>'Siberia',:full_abbreviation=>'sib',},
      {:name=>'Silesia',:full_abbreviation=>'sil',},
      {:name=>'Skagerrak',:full_abbreviation=>'ska',},
      {:name=>'Southern Algeria',:full_abbreviation=>'sou',:aliases=>[ 'sal', 'salg'],},
      {:name=>'Spain (east coast)',:full_abbreviation=>'spa/ec',:aliases=>[ 'spa(ec)', 'spain/ec', 'spain(ec)', 'spa (ec)', 'spain (ec)'],},
      {:name=>'Spain (north coast)',:full_abbreviation=>'spa/nc',:aliases=>[ 'spa(nc)', 'spain/nc', 'spain(nc)', 'spa (nc)', 'spain (nc)'],},
      {:name=>'Spain (west coast)',:full_abbreviation=>'spa/wc',:aliases=>[ 'spa(wc)', 'spain/wc', 'spain(wc)', 'spa (wc)', 'spain (wc)'],},
      {:name=>'Spain',:full_abbreviation=>'spa',},
      {:name=>'St Petersburg (north coast)',:full_abbreviation=>'stp/nc',:aliases=>[ 'stp(nc)', 'stpete/nc', 'stpete(nc)', 'st. petersburg/nc', 'stp (nc)'],},
      {:name=>'St Petersburg (south coast)',:full_abbreviation=>'stp/sc',:aliases=>[ 'stp(sc)', 'stpete/sc', 'stpete(sc)', 'st. petersburg/sc', 'stp (sc)'],},
      {:name=>'St Petersburg',:full_abbreviation=>'stp',:aliases=>[ 'stpete', 'st. petersburg', 'st.petersburg'],},
      {:name=>'Sweden',:full_abbreviation=>'swe',},
      {:name=>'Switzerland',:full_abbreviation=>'swi',},
      {:name=>'Trieste',:full_abbreviation=>'tri',},
      {:name=>'Tripolitania',:full_abbreviation=>'trp',:aliases=>[ 'trip', 'tripoli'],},
      {:name=>'Tunisia',:full_abbreviation=>'tun',:aliases=>[ 'tunis'],},
      {:name=>'Tyrolia',:full_abbreviation=>'tyr',:aliases=>[ 'tyl', 'trl'],},
      {:name=>'Tyrrhenian Sea',:full_abbreviation=>'tys',:aliases=>[ 'tyrr', 'tyrrhenian', 'tyn', 'tyh'],},
      {:name=>'Ukraine',:full_abbreviation=>'ukr',},
      {:name=>'Venetia',:full_abbreviation=>'ven',:aliases=>[ 'venice'],},
      {:name=>'Vienna',:full_abbreviation=>'vie',},
      {:name=>'Wales',:full_abbreviation=>'wal',},
      {:name=>'Warsaw',:full_abbreviation=>'war',},
      {:name=>'Western Mediterranean',:full_abbreviation=>'wes',:aliases=>[ 'wmed', 'west', 'western', 'westmed', 'wms', 'wme', 'wmd', 'west med'],},
      {:name=>'Yorkshire',:full_abbreviation=>'yor',:aliases=>[ 'york', 'yonkers'],},
    ]
    @map = @reader.read('1900')
  end

  def test_visual_name
    assert_equal '1900', @map.visual, "Map names do not match"
  end
end